"""Add reviewed position imports

Revision ID: 0004_stage1_position_imports
Revises: 0003_immutable_position_revisions_and_identifiers
Create Date: 2026-10-02 09:01:16.860368
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0004_stage1_position_imports"
down_revision: str | None = "0003_immutable_position_revisions_and_identifiers"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "private_files",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("storage_key", sa.String(length=100), nullable=False),
        sa.Column("original_name", sa.String(length=200), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("content_hash", name="uq_private_file_content_hash"),
        sa.UniqueConstraint("storage_key", name="uq_private_file_storage_key"),
    )
    op.create_table(
        "imports",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("file_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=True),
        sa.Column("fund_security_id", sa.Uuid(), nullable=True),
        sa.Column("effective_date", sa.Date(), nullable=False),
        sa.Column("source_label", sa.String(length=100), nullable=False),
        sa.Column("parser_version", sa.String(length=80), nullable=False),
        sa.Column(
            "column_mapping",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("file_sha256", sa.String(length=64), nullable=False),
        sa.Column("identity_hash", sa.String(length=64), nullable=False),
        sa.Column("interpretation_hash", sa.String(length=64), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("review_revision", sa.Integer(), server_default="1", nullable=False),
        sa.Column("expected_account_revision", sa.Integer(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column("batch_count", sa.Integer(), nullable=False),
        sa.Column("duplicate_of_import_id", sa.Uuid(), nullable=True),
        sa.Column("staging_snapshot_id", sa.Uuid(), nullable=True),
        sa.Column("published_snapshot_id", sa.Uuid(), nullable=True),
        sa.Column(
            "diagnostics",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(kind = 'positions' AND account_id IS NOT NULL AND "
            "fund_security_id IS NULL) OR "
            "(kind = 'fund' AND account_id IS NULL AND "
            "fund_security_id IS NOT NULL)",
            name="ck_import_scope",
        ),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["duplicate_of_import_id"], ["imports.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["file_id"], ["private_files.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["fund_security_id"], ["securities.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["published_snapshot_id"], ["position_snapshots.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["staging_snapshot_id"], ["position_snapshots.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key", name="uq_import_idempotency_key"),
    )
    op.create_index("ix_imports_file", "imports", ["file_id"], unique=False)
    op.create_index(
        "ix_imports_identity",
        "imports",
        ["identity_hash", "interpretation_hash"],
        unique=False,
    )
    op.create_table(
        "security_issuer_mapping_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("security_id", sa.Uuid(), nullable=False),
        sa.Column("previous_issuer_id", sa.Uuid(), nullable=True),
        sa.Column("new_issuer_id", sa.Uuid(), nullable=True),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column("changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["new_issuer_id"], ["issuers.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["previous_issuer_id"], ["issuers.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["security_id"], ["securities.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "import_batches",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("import_id", sa.Uuid(), nullable=False),
        sa.Column("purpose", sa.String(length=32), nullable=False),
        sa.Column("review_revision", sa.Integer(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["import_id"], ["imports.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "import_id",
            "purpose",
            "review_revision",
            "ordinal",
            name="uq_import_batch_identity",
        ),
    )
    op.create_index(
        "ix_import_batches_import",
        "import_batches",
        ["import_id", "purpose"],
        unique=False,
    )
    op.create_table(
        "import_review_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("import_id", sa.Uuid(), nullable=False),
        sa.Column("review_revision", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column(
            "change_payload",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["import_id"], ["imports.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "import_id", "review_revision", name="uq_import_review_revision"
        ),
    )
    op.create_table(
        "import_rows",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("import_id", sa.Uuid(), nullable=False),
        sa.Column("row_number", sa.Integer(), nullable=False),
        sa.Column(
            "raw_payload",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("raw_identifier", sa.String(length=2000), nullable=True),
        sa.Column("raw_name", sa.String(length=2000), nullable=True),
        sa.Column("raw_asset_type", sa.String(length=2000), nullable=True),
        sa.Column("raw_quantity", sa.String(length=2000), nullable=True),
        sa.Column("raw_price", sa.String(length=2000), nullable=True),
        sa.Column("raw_currency", sa.String(length=200), nullable=True),
        sa.Column("raw_weight_value", sa.String(length=100), nullable=True),
        sa.Column("raw_weight_unit", sa.String(length=24), nullable=True),
        sa.Column("security_id", sa.Uuid(), nullable=True),
        sa.Column(
            "normalized_quantity", sa.Numeric(precision=28, scale=10), nullable=True
        ),
        sa.Column(
            "normalized_price", sa.Numeric(precision=24, scale=10), nullable=True
        ),
        sa.Column(
            "normalized_weight", sa.Numeric(precision=18, scale=10), nullable=True
        ),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("row_status", sa.String(length=24), nullable=False),
        sa.Column("excluded", sa.Boolean(), nullable=False),
        sa.Column("correction_reason", sa.Text(), nullable=True),
        sa.Column(
            "diagnostics",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["import_id"], ["imports.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["security_id"], ["securities.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("import_id", "row_number", name="uq_import_row_number"),
    )
    op.create_index(
        "ix_import_rows_import_status",
        "import_rows",
        ["import_id", "row_status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_import_rows_import_status", table_name="import_rows")
    op.drop_table("import_rows")
    op.drop_table("import_review_events")
    op.drop_index("ix_import_batches_import", table_name="import_batches")
    op.drop_table("import_batches")
    op.drop_table("security_issuer_mapping_events")
    op.drop_index("ix_imports_identity", table_name="imports")
    op.drop_index("ix_imports_file", table_name="imports")
    op.drop_table("imports")
    op.drop_table("private_files")
    # ### end Alembic commands ###
