"""Add reviewed fund compositions

Revision ID: 0005_fund_compositions
Revises: 0004_stage1_position_imports
Create Date: 2026-10-02 09:47:50.282280
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0005_fund_compositions"
down_revision: str | None = "0004_stage1_position_imports"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fund_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("fund_security_id", sa.Uuid(), nullable=False),
        sa.Column("import_id", sa.Uuid(), nullable=False),
        sa.Column("review_revision", sa.Integer(), nullable=False),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source", sa.String(length=100), nullable=False),
        sa.Column("source_url", sa.String(length=500), nullable=True),
        sa.Column("parser_version", sa.String(length=80), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column(
            "reported_weight", sa.Numeric(precision=18, scale=10), nullable=False
        ),
        sa.Column(
            "recognized_weight", sa.Numeric(precision=18, scale=10), nullable=False
        ),
        sa.Column("quality_status", sa.String(length=24), nullable=False),
        sa.Column(
            "diagnostics",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["fund_security_id"], ["securities.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["import_id"], ["imports.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "import_id", "review_revision", name="uq_fund_import_revision"
        ),
    )
    op.create_index(
        "ix_fund_snapshots_selection",
        "fund_snapshots",
        ["fund_security_id", "as_of", "status"],
        unique=False,
    )
    op.create_table(
        "fund_lines",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("row_number", sa.Integer(), nullable=False),
        sa.Column("review_row_id", sa.Uuid(), nullable=False),
        sa.Column("security_id", sa.Uuid(), nullable=True),
        sa.Column("weight", sa.Numeric(precision=18, scale=10), nullable=False),
        sa.Column("asset_type", sa.String(length=24), nullable=False),
        sa.Column("raw_identifier", sa.String(length=2000), nullable=True),
        sa.Column("raw_name", sa.String(length=2000), nullable=True),
        sa.Column("match_status", sa.String(length=24), nullable=False),
        sa.ForeignKeyConstraint(
            ["review_row_id"], ["import_rows.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["security_id"], ["securities.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"], ["fund_snapshots.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("snapshot_id", "row_number", name="uq_fund_line_row"),
    )
    op.create_index(
        "ix_fund_lines_snapshot", "fund_lines", ["snapshot_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_fund_lines_snapshot", table_name="fund_lines")
    op.drop_table("fund_lines")
    op.drop_index("ix_fund_snapshots_selection", table_name="fund_snapshots")
    op.drop_table("fund_snapshots")
    # ### end Alembic commands ###
