/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Health */
    get: operations['health_health_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/health/ready': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Ready */
    get: operations['ready_health_ready_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/accounts': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Accounts */
    get: operations['get_accounts_v1_accounts_get']
    put?: never
    /** Post Account */
    post: operations['post_account_v1_accounts_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/accounts/{account_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /** Patch Account */
    patch: operations['patch_account_v1_accounts__account_id__patch']
    trace?: never
  }
  '/v1/accounts/{account_id}/positions': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Positions */
    get: operations['get_positions_v1_accounts__account_id__positions_get']
    /** Put Positions */
    put: operations['put_positions_v1_accounts__account_id__positions_put']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/securities/resolve': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Security Resolution */
    get: operations['get_security_resolution_v1_securities_resolve_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** AccountCreate */
    AccountCreate: {
      /** Account Type */
      account_type: string
      /** Base Currency */
      base_currency: string
      /** Name */
      name: string
    }
    /** AccountPatch */
    AccountPatch: {
      /** Account Type */
      account_type?: string | null
      /** Active */
      active?: boolean | null
      /** Base Currency */
      base_currency?: string | null
      /** Name */
      name?: string | null
    }
    /** AccountRead */
    AccountRead: {
      /** Account Type */
      account_type: string
      /** Active */
      active: boolean
      /** Base Currency */
      base_currency: string
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Name */
      name: string
      /** Source Type */
      source_type: string
    }
    /** ErrorResponse */
    ErrorResponse: {
      /** Detail */
      detail: string
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /** HealthResponse */
    HealthResponse: {
      /** Status */
      status: string
    }
    /** PositionInput */
    PositionInput: {
      /** Currency */
      currency: string
      /** Quantity */
      quantity: string
      /** Reported Price */
      reported_price?: string | null
      /**
       * Security Id
       * Format: uuid
       */
      security_id: string
    }
    /** PositionLineRead */
    PositionLineRead: {
      /** Currency */
      currency: string
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Price As Of */
      price_as_of: string | null
      /** Quality Status */
      quality_status: string
      /** Quantity */
      quantity: string
      /** Reported Price */
      reported_price: string | null
      /** Reported Value */
      reported_value: string | null
      security: components['schemas']['SecurityRead']
      /** Source */
      source: string
    }
    /** PositionReplace */
    PositionReplace: {
      /**
       * Effective Date
       * Format: date
       */
      effective_date: string
      /** Expected Revision */
      expected_revision: number | null
      /** Positions */
      positions: components['schemas']['PositionInput'][]
    }
    /** PositionSnapshotRead */
    PositionSnapshotRead: {
      /**
       * Account Id
       * Format: uuid
       */
      account_id: string
      /**
       * Effective Date
       * Format: date
       */
      effective_date: string
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Positions */
      positions: components['schemas']['PositionLineRead'][]
      /** Revision */
      revision: number
      /** Source */
      source: string
    }
    /** PositionsEnvelope */
    PositionsEnvelope: {
      snapshot: components['schemas']['PositionSnapshotRead'] | null
    }
    /** SecurityRead */
    SecurityRead: {
      /** Currency */
      currency: string
      /** Display Ticker */
      display_ticker: string | null
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Name */
      name: string
      /** Security Type */
      security_type: string
    }
    /** SecurityResolution */
    SecurityResolution: {
      /** Matches */
      matches: components['schemas']['SecurityRead'][]
      /**
       * Status
       * @enum {string}
       */
      status: 'resolved' | 'ambiguous' | 'unknown'
    }
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>
      /** Input */
      input?: unknown
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  health_health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthResponse']
        }
      }
    }
  }
  ready_health_ready_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthResponse']
        }
      }
    }
  }
  get_accounts_v1_accounts_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AccountRead'][]
        }
      }
      /** @description Requested resource not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Revision or state conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Database unavailable */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  post_account_v1_accounts_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['AccountCreate']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AccountRead']
        }
      }
      /** @description Requested resource not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Revision or state conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
      /** @description Database unavailable */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  patch_account_v1_accounts__account_id__patch: {
    parameters: {
      query?: never
      header?: never
      path: {
        account_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['AccountPatch']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AccountRead']
        }
      }
      /** @description Requested resource not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Revision or state conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
      /** @description Database unavailable */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  get_positions_v1_accounts__account_id__positions_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        account_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PositionsEnvelope']
        }
      }
      /** @description Requested resource not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Revision or state conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
      /** @description Database unavailable */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  put_positions_v1_accounts__account_id__positions_put: {
    parameters: {
      query?: never
      header?: never
      path: {
        account_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['PositionReplace']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PositionSnapshotRead']
        }
      }
      /** @description Requested resource not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Revision or state conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
      /** @description Database unavailable */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  get_security_resolution_v1_securities_resolve_get: {
    parameters: {
      query: {
        q: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SecurityResolution']
        }
      }
      /** @description Requested resource not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Revision or state conflict */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
      /** @description Database unavailable */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
}
